version: "3.7"
services:
  postgresserver:
    container_name: postgresserver
    image: postgres
    ports:
      - 5432:5432
    networks:
      - app_network
  app-docker:
    container_name: app-docker
    image: app-docker:1.0
    ports:
      - 8080:8080
    depends_on:
      - postgresserver
    environment:
      - HOST=
      - PORT=
    networks:
      - app_network

networks:
  app_network:
    name: app_network

