CREATE SEQUENCE MCUSTOMER_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE MACCOUNT_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE MCUSTOMER (
    MCUSTOMERPK INTEGER NOT NULL PRIMARY KEY,
    CUSTOMERNO CHAR(20) DEFAULT '',
    CUSTOMERNAME CHAR(30) DEFAULT '',
    UPDATEDBY CHAR(15) DEFAULT '',
    LASTUPDATED TIMESTAMP DEFAULT NULL
);

CREATE TABLE MACCOUNT (
    MACCOUNTPK INTEGER NOT NULL PRIMARY KEY,
    MCUSTOMERFK INTEGER,
    ACCNO CHAR(20) DEFAULT '',
    ACCNAME CHAR(30) DEFAULT '',
    UPDATEDBY CHAR(15) DEFAULT '',
    LASTUPDATED TIMESTAMP DEFAULT NULL
);
ALTER TABLE MACCOUNT ADD CONSTRAINT MACCOUNT_FK1 FOREIGN KEY (MCUSTOMERFK) REFERENCES MCUSTOMER (MCUSTOMERPK) ON DELETE CASCADE ON UPDATE NO ACTION;